### ISSUE TITLE
"Pruned Events" vs "Other Events" vs "Other Features"

### ISSUE THREAD

**Issue by aminnayebi** [feedzai/timeshap#14]
By looking at the `cell_data` dataframe, I am seeing two types of entry for the `Event` column, i.e., "Pruned Events" and "Other Events". Could you please explain how different they are?
<img width="543" alt="image" src="https://user-images.githubusercontent.com/39872170/165948621-b9b6806e-a97f-414c-91d1-5748b9a04381.png">

My other question is that even if I set the `top_x_feats` in `cell_dict` to be total number of features in my data, still the `cell_data` data frame contains some rows in which there is a non-zero shap value for "Other Features", for example:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/39872170/165950741-7d318cbf-1675-4a17-9563-a3fe0956b781.png">
How is that possible? There shouldn't be any "Other Features" as I have all the features separately listed in the `cell_data` data frame.

**Comment by JoaoPBSousa** [comment]
Hello @aminnayebi,

`"Pruned Events"` are events that are pruned by the temporal coalition pruning algorithm. `"Other Events"` are events that are not pruned, but are deemed less relevant for the cell level calculation through the `top_x_events` or `event_threshold` parameters. 

`"Pruned Events"`  are represented in dark gray, `(E-59 to E-7)`. `"Other Events"` are represented in light gray `(E-6,E-5,E-3,E-2,E-1,)`

<img src="https://user-images.githubusercontent.com/36603746/166424450-f5f20e14-6dee-4c00-9159-ec7135ba6d66.png" width="400" height="235" />


Regarding your question about the `"Other Features"` when there should not be `"Other Features"`, this is indeed wrong and I have pushed the correct code to the repo. The importance for this group was always being calculated, but in the extreme case that you described where there are no `"Other Features"` the importance being assigned by TimeSHAP was noise, since no perturbations were being calculated.

Thank you for noting this issue, and let me know if you have any further questions.

**Comment by aminnayebi** [comment]
Thank you very much. Closing the issue!
