### ISSUE TITLE
Apply Timeshap without pruning

### ISSUE THREAD

**Issue by sharonzag** [feedzai/timeshap#30]
Hi, 
I would like to use Timeshap on my LSTM model fitted on sequences of events (we are using one feature only).
Our model is working well but since it is a black box model, we want to find a way to explain it.
I want to know if we can apply Timeshap because the sequence of events we are using includes the last occurrence of each event
 so we have sequences of distinct events.
As we are using distinct sequences of events only, we don't want to apply the pruning algorithm. 
Could you show me how I can get local/global reports without using any pruning
Thank you

**Comment by JoaoPBSousa** [comment]
Hello @GabrielleAzoulay 

When using a dataset with one feature, feature-level and cell-level explanations become redundant, as event-level level explanations can encompass all necessary information. For this reason, local/global reports are redundant, as you can use the event-level local/global explanations.

Regarding how to use get local/global reports without pruning, currently there isn't a straightforward way to skip it when using these reports, we will be adding one in the coming weeks. Since you can obtain all the information you require using only **event-level explanations**, you can manually set the pruning index to 0.  

```
pruning_idx = 0

event_dict = {'rs': 42, 'nsamples': 32000}
event_data = local_event(f_hs, pos_x_data, event_dict, positive_sequence_id, sequence_id_feat, average_event, pruning_idx)
event_plot = plot_event_heatmap(event_data)
event_plot
```

Another approach to try to skip the pruning, would be to set the pruning tolerance to 0. This way pruning would be calculated, but most likely TimeSHAP would not find a suitable pruning index that fits the 0 tolerance and nothing would be pruned.

In order for me to give you more specific information regarding your usecase, could you please clarify what you meant by `"the sequence of events we are using includes the last occurrence of each event so we have sequences of distinct events."`

Hope I could be helpful, If this does not help, feel free to provide more details so I can try to help you.

**Comment by GabrielleAzoulay** [comment]
Hi,
Thank you for your explanations 
What I mean by "the sequence of events we are using includes the last occurrence of each event so we have sequences of distinct events."  is that the sequences we are using could include several times the same event and so could be very long. 
Based on an analysis we have done, we decided to use sequences of distinct events only, which means that we filtered out duplicated events and we keep only the last occurrence of each event in the sequence. 
Here is a simple example:
![screenshot_df](https://user-images.githubusercontent.com/24206999/225606712-02a24d69-f279-4ae4-8542-b42184b694ba.png)

**Comment by GabrielleAzoulay** [comment]
I tried to run your code with my dataset but event with pruning_idx = 0, I get the same error message

**Comment by JoaoPBSousa** [comment]
Hi @GabrielleAzoulay, 
Could you please provide us with the error message and a code snippet so I can try to help you?

**Comment by JoaoPBSousa** [comment]
Closed this issue due to inactivity. If this error persists or you have any further questions feel free to re-open the issue or create a new one.
