### ISSUE TITLE
How does TimeShap handle missing values (NA)?

### ISSUE THREAD

**Issue by edpclau** [feedzai/timeshap#40]
Hi,

I have a question regarding how TimeShap handles missing values (NA). To calculate the baseline, TimeShap uses the numerical average of the features, but doing this causes an error in the Shap Value estimation since the NA values in my features are informative for the model's performance. What would you recommend in this case? Should I attempt to impute these values or use a different method than TimeShap?

**Comment by JoaoPBSousa** [comment]
Hello @edpclau ,

TimeSHAP assumes that the data has no missing values. Consider imputing them with a domain relevant value but note that the explanations will be influenced by this. 

I hope this answer is helpful. If you have any further questions feel free to ask.

**Comment by JoaoPBSousa** [comment]
Closed this issue due to inactivity. If you have any further questions feel free to re-open the issue or create a new one.

**Comment by edpclau** [comment]
Hi @JoaoPBSousa,
Thank you for your respnse!

I have a couple of follow up questions. Is the reason that TimeShap assumes no missing values related to KernelShap? If so, what if I replaced the KernelShap part of TimeShap for PermutationShap? Do you know of any tools similar to TimeShap which can accomplish this task?

**Comment by JoaoPBSousa** [comment]
Hi @edpclau ,

In order for me to be able to help you, could you please clarify what you mean by missing values and if you do any processing to them?
Are your missing values in the data represented by NaN values, and you input them in order to train a model, or are you using a model that receives data with these untreated missing values directly?

**Comment by edpclau** [comment]
Hi @JoaoPBSousa,

By missing values, I mean NAs and NaN values in the data. Many of these missing values are due to uneven sampling or the absence of the value. For example, if a specific drug was not administered in time step 2, it would appear as an NA. I have tried to do some imputation but I can't impute everything. I use this data with missing values to train a [ GRU-D model](https://github.com/WenjieDu/PyPOTS). The task the model is trained to do is binary classification. 

However, while the model can learn with the missing values, I'm having trouble with TimeSHAP, especially when calculating the baseline. This is why I thought that maybe switching from KernelSHAP to PermutationExplainer would be better since it seems it doesn't need a baseline value (i could be wrong).

**Comment by JoaoPBSousa** [comment]
Hello @edpclau ,

Thank you for informing about these types of models.

Based on the theoretical perspective, I don't see any inherent reasons why TimeSHAP wouldn't be able to work with missing values. The errors you are experiencing are, most likely, related to specific implementations, which can be addressed and resolved.

Feel free to provide more details about the errors you are encountering so that we can further analyze and determine if they can be fixed or if TimeSHAP is indeed not compatible with this type of data.

**Comment by edpclau** [comment]
Hi @JoaoPBSousa ,

I'm attaching a [colab notebook](https://drive.google.com/file/d/1BAYRiNcKJBCt89me3hLXPe7fnGosCXHY/view?usp=sharing) with the model and type of data I'm having issues with.

**Comment by JoaoPBSousa** [comment]
Hello @edpclau ,

Apologies for the delay, as we were on PTO.

The issue you're encountering is related to the data format used in the notebook. Specifically, the data being passed to TimeSHAP is in dictionary format. To address this, you need to convert the data into either a numpy array or a pandas dataframe, which are the formats supported by TimeSHAP.

Given that the model you are working with requires data in dictionary format for scoring instances, you'll need to develop a model wrapper. This wrapper will facilitate the conversion of numpy array datasets used by TimeSHAP into dictionary instances suitable for the model, and vice versa.

I hope this answer is helpful. If you have any further questions feel free to ask.

**Comment by JoaoPBSousa** [comment]
Closed this issue due to inactivity. If you have any further questions feel free to re-open the issue or create a new one.
