### ISSUE TITLE
Does the plot demonstrate that when my feature has a high value, the output either increases or decreases, or vice versa?

### ISSUE THREAD

**Issue by janakmpatel** [feedzai/timeshap#45]
I want to find the root cause of my model using Timeshap. Does it have any plot like shap (beeswarm plot) which shows how high or low feature value will increase or decrease model output.

**Comment by JoaoPBSousa** [comment]
Hello @janakmpatel ,

Currently, we do not have any plots that relate feature values with explanation values. However, TimeSHAP outputs the explanation values in a CSV file, which allows users to create such plots. 
If you implement such plots, please feel free to share the code with us so that we can integrate them into the repository.

If you have any questions or need assistance, please don't hesitate to comment on this issue or open a new one.

**Comment by janakmpatel** [comment]
Thanks a lot @JoaoPBSousa. Surely, I will share the code if I will implement such plots.
