### ISSUE TITLE
Issue in reproducing TimeSHAP Tutorial - TensorFlow - AReM dataset 

### ISSUE THREAD

**Issue by grzechowiak** [feedzai/timeshap#9]
Foremost, thanks for the library, really great job! 

I am trying to reproduce your TimeSHAP Tutorial for TF and I am having an issue in the section for Global Explanations when running the `global_report()` function - screen below:

![image](https://user-images.githubusercontent.com/25528037/162435286-5a51d62c-2854-4d8c-b6eb-657c0ac857e2.png)

The error refers to encoding the `\u2264` character which is a sign: `<=`. I was trying to solve that myself by modifying the `pruning.py` function according to the error by adding `encoding="utf-8"` in line 326 `with open(file_path, 'a', newline='') as file:`, however it didn't solve the problem. Any advice is very welcome!

Also, for consistency, I want to mention that I had a problem loading the data - showing the error screens below. I was able to solve the problem only by deleting 2 datasets: `cycling/dataset9.csv` and `cycling/dataset14csv` and the rest of the code worked.

1/2
![image](https://user-images.githubusercontent.com/25528037/162435925-709b9b62-fd99-4f4b-9639-6d75f06ff07e.png)
2/2
![image](https://user-images.githubusercontent.com/25528037/162436415-60e4526a-8601-4507-bb28-c07350fd1ed1.png)

**Comment by JoaoPBSousa** [comment]
Hello @grzechowiak ,

Regarding the first issue, I suspect this is due to the OS you are using. On the persisted pruning data we write the character  `\u2264`. A quick fix for your issue is to replace this character with another string/char. Replace symbols in lines:
- https://github.com/feedzai/timeshap/blob/main/src/timeshap/explainer/pruning.py#L80;
- https://github.com/feedzai/timeshap/blob/main/src/timeshap/explainer/pruning.py#L145; (This is a `>`. Will probably cause issues also, so maybe replace it right away)
- https://github.com/feedzai/timeshap/blob/main/src/timeshap/explainer/pruning.py#L146;
- https://github.com/feedzai/timeshap/blob/main/src/timeshap/plot/pruning.py#L63.

About the dataset loading issue, this is known (documented on [README](https://github.com/feedzai/timeshap/blob/main/notebooks/AReM/README.md) ). This is due to the data itself being malformed on the UCI repo. We uploaded a fixed version of the datasets to the repo.

Please let me know if this fixes worked, and if you have any further question don't hesitate to contact us.

**Comment by grzechowiak** [comment]
Hello @JoaoPBSousa ,

Thank you for your quick answer! Your solution helped with the string, however, I have got another error (the same line), this time regarding the `'Shapley Value'`. Any ideas why the error pop up? Please see the screen below.

![image](https://user-images.githubusercontent.com/25528037/162694108-aad5090a-2038-408b-bafb-d25732604b85.png)

**Comment by JoaoPBSousa** [comment]
Hello @grzechowiak,

This issue is due to the event data `event_data` passed to the `plot_global_event` method not having the `Shapley Value` key. 
We can run the code with no issues, so I cannot help you without further information.
Make sure that the `event_data` variable has all the necessary keys, "Shapley Value" included. Is it possible that when you edited the code to fix the string issue, you changed something on the method?

If the issue persists, could you please provide further information so I can help you?

**Comment by grzechowiak** [comment]
Hello @JoaoPBSousa ,

Thanks for the answer! Finally, I was able to execute the function. I am not exactly sure what was causing the error, but I reinstalled the TimeSHAP and also I deleted the outputs in the output folder. Once the function had to recreate and save into the outputs folder again, the function worked. Anyway, thanks for the help!
